// <auto-generated />
using DoAn.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoAn.Migrations
{
    [DbContext(typeof(DPContext))]
    [Migration("20201126115411_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DienThoaiModel", b =>
                {
                    b.Property<string>("MaDongDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<string>("DongDienThoaiIMEI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("GiaKM")
                        .HasColumnType("real");

                    b.Property<string>("Hinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHangSX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDongDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDongDT");

                    b.HasIndex("DongDienThoaiIMEI");

                    b.ToTable("DienThoai");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DongDienThoaiModel", b =>
                {
                    b.Property<string>("IMEI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDongDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauSac")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IMEI");

                    b.ToTable("DongDienThoai");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DienThoaiModel", b =>
                {
                    b.HasOne("DoAn.Areas.Admin.Models.DongDienThoaiModel", "DongDienThoai")
                        .WithMany("listDienThoai")
                        .HasForeignKey("DongDienThoaiIMEI");

                    b.Navigation("DongDienThoai");
                });

            modelBuilder.Entity("DoAn.Areas.Admin.Models.DongDienThoaiModel", b =>
                {
                    b.Navigation("listDienThoai");
                });
#pragma warning restore 612, 618
        }
    }
}
